channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - nomkl
  - polars
  - xlsx2csv
  - psutil
  - sqlparse
  - sqlglot
  - numpy
  - pyarrow
  - pandas
  - lxml
  - pyreadstat  
  - odfpy
  - xlsxwriter
  - pyxlsb
  - xlrd
  - pandavro
  - python-snappy
  - pip
  - pip:
    - lief
    - duckdb
    - cx-Freeze
    - openpyxl
