channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - nomkl
  - polars
  - xlsx2csv
  - psutil
  - sqlparse
  - sqlglot
  - numpy
  - pyarrow
  - pandas
  - lxml
  - pyreadstat  
  - odfpy
  - xlsxwriter
  - pyxlsb
  - xlrd
  - pandavro
  - python-snappy
  - pytables=3.7
  - pyorc
  - pip
  - pip:
    - lief
    - duckdb
    - cx-Freeze
    - openpyxl
