channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - nomkl
  - polars=0.19.13
  - xlsx2csv
  - psutil
  - sqlparse
  - sqlglot
  - pyarrow
  - pandas=2.0.3
  - lxml
  - pyreadstat  
  - odfpy
  - xlsxwriter
  - pyxlsb
  - xlrd
  - pandavro
  - python-snappy
  - pytables=3.7
  - pyorc
  - pip
  - pip:
    - lief
    - duckdb
    - cx-Freeze
    - openpyxl
    - pytest
    - requests
    - numpy==1.23.5
