name: Debug

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      MSI_URL: ${{ steps.upload_msi.outputs.MSI_URL }}
    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

    steps:
      - name: Set VERSION variable
        shell: bash
        id: deb
        run: |
          echo "VERSION=https://factotum.blob.core.windows.net/factotum/1.0.14/Factotum.msi" >> $GITHUB_OUTPUT

      - name: Login to Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Upload MSI to Azure Blob Storage and get URL
        if: runner.os == 'Windows'
        id: upload_msi
        shell: bash
        run: |
          name="1.0.14/Factotum.msi"
          url=$(az storage blob url --name $name --container-name factotum)
          echo $url
          echo "MSI_URL=$url" >> $GITHUB_OUTPUT


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        MSI_URL: ${{ needs.build.outputs.MSI_URL }}

      - name: Print vars
        run: |
          echo $MSI_URL
          echo "aaaaa"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        run: |
          version=${{ github.event.inputs.version }}
          echo $MSI_URL
          gh release create "v${version}" --repo ${{ github.repository }} --title "Release v${version}" --notes "
          Windows x64 Installer [Factotum.msi]($MSI_URL)
          "