name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      MSI_NAME: ${{ steps.upload_msi.outputs.MSI_NAME }}
      DMG_X64_NAME: ${{ steps.upload_dmg_x64.outputs.DMG_X64_NAME }}
      DMG_ARM64_NAME: ${{ steps.upload_dmg_arm64.outputs.DMG_ARM64_NAME }}
    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}

    steps:
      - name: Set VERSION variable
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Login to Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Xcode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash powershell

      - name: Build python
        shell: powershell
        run: python setup.py build

      - name: Install node dependencies
        run: yarn install

      - name: Install Wix Toolset
        if: runner.os == 'Windows'
        run: |
          choco install wixtoolset -y --version 3.11.2
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        
      - name: Setup env variables for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "${{ secrets.PFX_BASE64 }}" | base64 --decode > certificate.pfx
          echo "CSC_LINK=${{ github.workspace }}/certificate.pfx" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.PFX_PASSWORD }}" >> $GITHUB_ENV

      - name: Set up env variables for MacOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > certificate.p12
          echo "CSC_LINK=${{ github.workspace }}/certificate.p12" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.P12_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV

      - name: Build Electron app
        run: npm run pack

      - name: Run Playwright tests
        run: npm run test

      - name: Make executables
        run: npm run dist

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: trace
          path: trace/

      - name: Upload MSI to Azure Blob Storage
        if: runner.os == 'Windows'
        id: upload_msi
        shell: bash
        run: |
          name="${{ env.VERSION }}/Factotum.msi"
          az storage blob upload --name $name --file "./dist/Factotum.msi" --container-name factotum --overwrite
          echo "MSI_NAME=$name" >> $GITHUB_OUTPUT

      - name: Upload DMG x64 to Azure Blob Storage
        if: runner.os == 'macOS'
        id: upload_dmg_x64
        run: |
          name="${{ env.VERSION }}/Factotum-x64.dmg"
          az storage blob upload --name $name --file "./dist/Factotum-x64.dmg" --container-name factotum --overwrite
          echo "DMG_X64_NAME=$name" >> $GITHUB_OUTPUT

      - name: Upload DMG arm64 to Azure Blob Storage
        if: runner.os == 'macOS'
        id: upload_dmg_arm64
        run: |
          name="${{ env.VERSION }}/Factotum-arm64.dmg"
          az storage blob upload --name $name --file "./dist/Factotum-arm64.dmg" --container-name factotum --overwrite
          echo "DMG_ARM64_NAME=$name" >> $GITHUB_OUTPUT

      - name: Upload DEB to Azure Blob Storage
        if: runner.os == 'Ubuntu'
        id: upload_deb
        shell: bash
        run: |
          name="${{ env.VERSION }}/Factotum-amd64.deb"
          az storage blob upload --name $name --file "./dist/Factotum-amd64.deb" --container-name factotum --overwrite
          echo "DEB_NAME=$name" >> $GITHUB_OUTPUT

      - name: Upload RPM to Azure Blob Storage
        if: runner.os == 'Ubuntu'
        id: upload_rpm
        shell: bash
        run: |
          name="${{ env.VERSION }}/Factotum-x86_64.rpm"
          az storage blob upload --name $name --file "./dist/Factotum-x86_64.rpm" --container-name factotum --overwrite
          echo "RPM_NAME=$name" >> $GITHUB_OUTPUT


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          MSI_NAME: ${{ needs.build.outputs.MSI_NAME }}
          DMG_X64_NAME: ${{ needs.build.outputs.DMG_X64_NAME }}
          DMG_ARM64_NAME: ${{ needs.build.outputs.DMG_ARM64_NAME }}
          DEB_NAME: ${{ needs.build.outputs.DEB_NAME }}
          RPM_NAME: ${{ needs.build.outputs.RPM_NAME }}
        run: |
          version=${{ github.event.inputs.version }}
          base_url="https://factotum.blob.core.windows.net/factotum/"
          gh release create "v${version}" --repo ${{ github.repository }} --title "Release v${version}" --notes "
          Windows x64 Installer [Factotum.msi](${base_url}${MSI_NAME})
          MacOS Intel [Factotum-x64.dmg](${base_url}${DMG_X64_NAME})
          MacOS Apple Silicon [Factotum-arm64.dmg](${base_url}${DMG_ARM64_NAME})
          Ubuntu x64 [Factotum-amd64.deb](${base_url}${DEB_NAME})
          RHEL x64 [Factotum-x86_64.rpm](${base_url}${RPM_NAME})
          "