name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set VERSION variable
        shell: bash
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Xcode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          init-shell: bash powershell

      - name: Install node dependencies
        run: yarn install

      - name: Build python
        shell: bash
        run: python setup.py build

      - name: Install Wix Toolset
        if: runner.os == 'Windows'
        run: |
          choco install wixtoolset -y --version 3.11.2
          echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        
      - name: Setup env variables for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          echo "${{ secrets.PFX_BASE64 }}" | base64 --decode > certificate.pfx
          echo "CSC_LINK=${{ github.workspace }}/certificate.pfx" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.PFX_PASSWORD }}" >> $GITHUB_ENV

      - name: Set up env variables for MacOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > certificate.p12
          echo "CSC_LINK=${{ github.workspace }}/certificate.p12" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.P12_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_ID=${{ secrets.APPLE_ID }}" >> $GITHUB_ENV
          echo "APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}" >> $GITHUB_ENV
          echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV

      - name: Build Electron app
        run: npm run pack

      - name: List dist dir
        run: echo $(ls dist dist/win-unpacked)
        shell: bash

      - name: Run Playwright tests
        run: npm run test

      - name: Make executables
        run: npm run dist

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: trace
          path: trace/

      - name: Upload MSI to Azure Blob Storage and get URL
        if: runner.os == 'Windows'
        uses: Azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            $context = New-AzStorageContext -StorageAccountName "${{ secrets.AZURE_STORAGE_ACCOUNT }}" -StorageAccountKey "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
            Set-AzStorageBlobContent -File "./dist/Factotum.msi" -Container "factotum" -Blob "${{ env.VERSION }}/Factotum.msi" -Context $context
            $blob = Get-AzStorageBlob -Container "factotum" -Blob "${{ env.VERSION }}/Factotum.msi" -Context $context
            $url = $blob.ICloudBlob.Uri.AbsoluteUri
            echo "MSI_URL=$url" >> $GITHUB_ENV

      - name: Upload DMG x64 to Azure Blob Storage and get URL
        if: runner.os == 'macOS'
        uses: Azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            $context = New-AzStorageContext -StorageAccountName "${{ secrets.AZURE_STORAGE_ACCOUNT }}" -StorageAccountKey "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
            Set-AzStorageBlobContent -File "./dist/Factotum-x64.dmg" -Container "factotum" -Blob "${{ env.VERSION }}/Factotum-x64.dmg" -Context $context
            $blob = Get-AzStorageBlob -Container "factotum" -Blob "${{ env.VERSION }}/Factotum-x64.dmg" -Context $context
            $url = $blob.ICloudBlob.Uri.AbsoluteUri
            echo "DMG_X64_URL=$url" >> $GITHUB_ENV

      - name: Upload DMG arm64 to Azure Blob Storage and get URL
        if: runner.os == 'macOS'
        uses: Azure/powershell@v1
        with:
          azPSVersion: '3.1.0'
          inlineScript: |
            $context = New-AzStorageContext -StorageAccountName "${{ secrets.AZURE_STORAGE_ACCOUNT }}" -StorageAccountKey "${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"
            Set-AzStorageBlobContent -File "./dist/Factotum-arm64.dmg" -Container "factotum" -Blob "${{ env.VERSION }}/Factotum-arm64.dmg" -Context $context
            $blob = Get-AzStorageBlob -Container "factotum" -Blob "${{ env.VERSION }}/Factotum-arm64.dmg" -Context $context
            $url = $blob.ICloudBlob.Uri.AbsoluteUri
            echo "DMG_ARM64_URL=$url" >> $GITHUB_ENV

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.PAT }}"
          automatic_release_tag: "v${{ env.VERSION }}"
          prerelease: false
          title: "Release v${{ env.VERSION }}"
          body: |
            Windows x64 Installer [Factotum.msi](${{ env.MSI_URL }})
            MacOS Intel [Factotum-x64.dmg](${{ env.DMG_X64_URL }})
            MacOS Apple Silicon [Factotum-arm64.dmg](${{ env.DMG_ARM64_URL }})