name: Test

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install node dependencies
        run: yarn install

      - name: Make Git Bash a default shell for npm on Windows
        if: runner.os == 'Windows'
        run: npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"

      - name: Setup Micromamba
        shell: bash
        run: npm run setup-micromamba

      - name: Setup venv
        shell: bash
        run: npm run setup-venv

      - name: Run Pytest tests
        shell: bash
        run: npm run server:test

      - name: Build server
        shell: bash
        run: npm run server:build

      - name: Install Wix Toolset
        if: runner.os == 'Windows'
        run: |
          choco install wixtoolset -y --version 3.14.1
          echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Build Electron app
        run: npm run pack

      - name: Run E2E tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run test:e2e

      - name: Run API tests
        run: npm run test:api

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: trace
          path: trace/