name: Test

on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.0

      - name: Install node dependencies
        run: yarn install

      - name: Install python dependencies
        run: npm run setup-venv

      - name: Decode PFX
        shell: bash
        run: |
          echo "${{ secrets.PFX_BASE64 }}" | base64 --decode > certificate.pfx
          echo "CSC_LINK=${{ github.workspace }}/certificate.pfx" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.PFX_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Electron app
        run: npm run pack

      - name: List dist dir
        run: echo $(ls . dist dist/win-unpacked)
        shell: bash

      - name: Run Electron App
        run: |
          start /wait dist\win-unpacked\Factotum.exe
          timeout /t 60 /nobreak

      - name: Run Playwright tests
        run: npm run test

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: |
            test-results/
